### ISSUE TITLE
Building fails with musl

### ISSUE THREAD

**Issue by Roba1993** [muja/unrar.rs#9]
Hi,

I really would like to use your library, but unfortunately the build fails with musl rust.

Thanks,
Robert

**Comment by muja** [comment]
Hi Robert.

I haven't used musl, could you explain what the problem is and how to reproduce?

**Comment by muja** [comment]
Hi, I keep getting the error

```
error occurred: Failed to find tool. Is `musl-g++` installed
```

And if I link `/usr/bin/g++` over to `/usr/bin/musl-g++`, my build works in your provided Docker container. But I'm not entirely sure how to solve this in this project....

**Comment by muja** [comment]
I just checked [emk/rust-musl-builder](https://github.com/emk/rust-musl-builder) and they had the [same issue](https://github.com/emk/rust-musl-builder/issues/53). They also solved it by [linking g++ over to musl-g++](https://github.com/emk/rust-musl-builder/blob/master/Dockerfile#L47). So my advice would be to use this image?

If you have any other concerns, please let me know.

**Comment by iddm** [comment]
> Hi, I keep getting the error
> 
> ```
> error occurred: Failed to find tool. Is `musl-g++` installed
> ```
> 
> And if I link `/usr/bin/g++` over to `/usr/bin/musl-g++`, my build works in your provided Docker container. But I'm not entirely sure how to solve this in this project....

I know this is an old thing. I am still using `clux/muslrust` because it is updated much more often than emk/rust-musl-builder and the latter had issues since, perhaps, 2017 or the day it appeared for about a few years, so I actually moved away from it to `clux/muslrust`. The fix **still works great**, I wonder why the project doesn't mention it in the README file.

**Comment by muja** [comment]
Hi @iddm I am not actively using musl it's just what I came across when looking for the error I guess (it's been 5 years). Feel free to open an issue if you run into problems, but if I understand correctly, everything's working great?

**Comment by iddm** [comment]
> Hi @iddm I am not actively using musl it's just what I came across when looking for the error I guess (it's been 5 years). Feel free to open an issue if you run into problems, but if I understand correctly, everything's working great?

I should apologise for breaking the silence here and disturbing you with this, but I just posted this to signal to others that the fix still works. The only solution I could find was this github issue, so I just wanted to let people know, that five years later it still works the same way. I am already creating a PR to mention the fix in the `clux/muslrust` project, so that the fix is more visible. Thank you!
